customhost = "pro2db.cb5ywanmfho5.us-east-1.rds.amazonaws.com"
customuser = "admin"
custompass = "admin123"
customdb = "pro2db"
custombucket = "pro2b"
customregion = "US East (N. Virginia) us-east-1"
